config/routes.rb
BadHair::Application.routes.draw do
  root :to => 'pages#index'
  post '/results' => 'pages#results'
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#sendemail'
  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
  patch "/hairstyles/:id/edit" => "hairstyles#edit"
  get "/users/custom_results/:hairstyle" => "users#custom_results", as: "custom"
  
  resources :hairstyles, :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :integer          not null, primary key
#  name                     :string(255)
#  email                    :text
#  password_digest          :string(255)
#  gender                   :string(255)
#  country                  :string(255)
#  city                     :text
#  humidity_susceptibility  :decimal(, )
#  thickness_susceptibility :decimal(, )
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :gender, :country, :city, :humidity_susceptibility, :thickness_susceptibility, :password, :password_confirmation
  has_many :hairstyles
  
  has_secure_password
  validates :email, :presence => true, :uniqueness => true, :length => { :minimum => 5 }
  validates :name, :presence => true, :uniqueness => true, :length => { :minimum => 2 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:create, :new]
  before_filter :check_if_admin, :only => [:index]
  before_filter :check_owner, :only => [:show]

  def new
    @user = User.new
  end

  def create
     @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_hairstyle_path
    else
      render :new
    end
  end

  def show
    @name = @current_user.name
    @hairstyles = @current_user.hairstyles
  end
  
  def custom_results
   # stuff to do with weather
    weather = Hairstyle.weather(@current_user.country.gsub(" ", "_"), @current_user.city.gsub(" ", "_"))
    @city = weather[:city]
    @country = weather[:country]
    @humidity = weather[:humidity]
    @temp = weather[:temp]
    @wind = weather[:wind]
    @pop = weather[:pop]
    @weather_icon = weather[:weather_icon]
    @wunderground_logo = weather[:wunderground_logo]
    
    # variables I need to print custom user information

    # Now for the prediction....
    
    current_hair = Hairstyle.find(params[:hairstyle])
    mods = current_hair.modifications.split("-")
    prediction_results = Hairstyle.prediction(current_hair.length, current_hair.curliness, current_hair.hygiene, @humidity, @wind, @pop, mods, @current_user.humidity_susceptibility.to_f, @current_user.thickness_susceptibility.to_f)
    @bad_hair_prediction = prediction_results[:prediction].first
    @message = prediction_results[:prediction][1]
    @div_id = prediction_results[:prediction][2]
    @background_url = prediction_results[:prediction][3]
    @reasons = prediction_results[:reasons]
  end

  def edit
    @user = User.find params[:id]
    
  end
  
  def update
    user = User.find params[:id]
    user.update_attributes params[:user]
    redirect_to user_path(@current_user.id)
  end

  private
  def check_if_logged_in
    redirect_to(root_path) if @current_user.nil?
  end

  def check_if_admin
    redirect_to(root_path) if @current_user.nil? || @current_user.admin == false
  end

  def check_owner
    redirect_to(root_path) if params[:id] != @current_user.id.to_s 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "user_form"} do |f| %> 
  <%= f.label :name %> 
  <%= f.text_field :name, :autofocus => true, :required => true %> 
  <%= f.label :email %> *
  <%= f.email_field :email %> 
  <%= f.label :gender %> 
  <%= f.select :gender, [['Female', 'Female'], ['Male', 'Male'], ['Transgender', 'Transgender'], ['Transsexual', 'Transsexual'], ['Intersex', 'Intersex'], ['Cross-dresser', 'Cross-dresser'], ['Female-to-male', 'Female-to-male'], ['Male-to-female', 'Male-to-female'], ['Other', 'Other'], ['Not telling', 'Not telling']] %>
  <%= f.label :country %>
  <%= f.country_select(:country, ["Australia", "Canada"]) %>
  <%= f.label :city %> 
  <%= f.text_field :city, :required => true %> 
  <%= f.label :humidity_susceptibility %> 
  <%= f.select :humidity_susceptibility, [['High', 0.90], ['Normal', 1.00], ['Low', 1.10]] %>
  <%= f.label "Hair thickness" %> 
  <%= f.select :thickness_susceptibility, [['Thin', 0.90], ['Normal', 1.00], ['Thick', 1.10]] %>
  <%= f.label :password %> 
  <%= f.password_field :password %>  
  <%= f.label :password_confirmation %>  
  <%= f.password_field :password_confirmation %>  
  <%= f.submit %>  
 <% end %>
 <p id="register_email">*Your email address let's us know you're a real person. We will never send you an email, or give your address to anyone else... because it's illegal and we hate getting emails ourselves.</p>
  

app/views/users/custom_results.html.erb
<div id="results_container">
  <h1><%= @current_user.name %>, it's going to be a <%= @bad_hair_prediction %></h1>
  <div style="background: url(<%= @background_url %>) no-repeat; background-size: contain;" class="results" id="<%= @div_id %>">
    <h1><%= @message %></h1>
  </div>
  <div class="results" id="results_moreinfo">

    <h2>Today's forecast for <%= @city %>, <%= @country %> <img src="<%= @weather_icon %>"></h2>
    <p>Temperature: <%= @temp %> C</p>
    <p>Humidity: <%= @humidity %>%</p>
    <p>Wind: <%= @wind %>kph</p>
    <p>Probability of precipitation: <%= @pop %>%</p>


    <% @reasons.each do |message| %>
      <p><%= message %></p>
    <% end %>

    <aside>Weather data supplied by <img alt="wunderground logo" src="<%= @wunderground_logo %>"> 
    </aside>
  </div>
</div>

app/views/users/edit.html.erb
<div id ="register">
  <div id="register_form" 

    <h1>Update <%= @current_user.name %>'s details.</h1>

  <%= render :partial => 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Register to generate customised predictions, and save multiple hairstyles.</h1>
<div id ="register">
  <div id="register_form">
    <% if @user.errors.any? %>
      <ol>
        <% @user.errors.full_messages.each do |msg| %> 
         <li> 
            <%= msg %> 
        </li>
        <% end %>
      </ol>
    <% end %>

    <%= render :partial => 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div id="results_container">
  <h1>Welcome <%= @name %></h1>
  <div id="user_container">
    <div id="user_sidenav">
      <ul>
        <li><%= link_to('Create a hairstyle', new_hairstyle_path) %></li>
        <li><%= link_to('Edit your details', edit_user_path) %></li>
      </ul>
    </div>
    <div id="user_hairstyles">
      <p>Your current hairstyles:<p>
      <% @hairstyles.each do |hairstyle| %>
      <p>
        <%= hairstyle.style_name %>
        (<%= link_to "Get Custom Prediction", custom_path(hairstyle) %> | <%= link_to("Edit", edit_hairstyle_path(hairstyle), :method => :patch) %> | <%= link_to("Delete", hairstyle_path(hairstyle), :method => :delete) %>)
        <% end %>
      </p>
    <div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>